version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:2000
    volumes:
      - .:/code
    ports:
      - 2000:2000
    depends_on:
      - db

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db  

volumes:
  postgres_data:    